services:
  kafka:
    image: apache/kafka:4.1.1
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  server-migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      DATABASE_URL: ${DATABASE_URL}

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    deploy:
      replicas: 2
    depends_on:
      kafka:
        condition: service_healthy
      server-migrations:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      KAFKA_BROKERS: brainwave-kafka:9092

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        SERVER_URL: ${SERVER_URL}
    deploy:
      replicas: 2
    environment:
      VITE_SERVER_URL: ${SERVER_URL}

volumes:
  kafka_data:
