services:
  database:
    image: postgis/postgis:17-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: "brainwave"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "brainwave"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
  kafka:
    image: apache/kafka:4.1.1
    ports:
      - 9092:9092
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  redis:
    image: redis:8
    ports:
      - 7878:6379
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
